define([
  'tests/spec/test/spec/client/player_spec',
'tests/spec/test/spec/client/touch_manager_spec',
'tests/spec/test/spec/mixin/acts_as_object_group_spec',
'tests/spec/test/spec/mixin/delegator_spec',
'tests/spec/test/spec/server/collision_circle_with_anti_arc',
'tests/spec/test/spec/server/collision_circle_with_anticircle_spec',
'tests/spec/test/spec/server/collision_circle_with_circle_spec',
'tests/spec/test/spec/server/game_world_renderer_spec',
'tests/spec/test/spec/server/graphic',
'tests/spec/test/spec/server/player_manager_spec',
'tests/spec/test/spec/server/player_spec',
'tests/spec/test/spec/server/player_stats_renderer_spec',
'tests/spec/test/spec/server/player_stats_template',
'tests/spec/test/spec/server/shapes_spec',
'tests/spec/test/spec/server/utils_spec',
'tests/spec/test/spec/server/vector_spec',
'tests/spec/test/spec/server/world_object_spec'
], function() {
});
